# ========================================== #
#            PAGELORE CONFIGURATION          #
# ========================================== #

settings:
  # The exact string used in your item's lore to split it into pages.
  # Recommendation: Keep it plain, do not use colors here.
  page-separator: "{page}"

  # Should the plugin play a sound when navigating pages? (true/false)
  play-sound: true
  # Sound type from Bukkit Sound Enum. Example: UI_BUTTON_CLICK, ENTITY_BAT_TAKEOFF
  sound-type: "ui.button.click"
  sound-volume: 1.0
  sound-pitch: 1.0

  # Set to true to print PlaceholderAPI checking values in the console.
  debug: false

  # Automatic inventory refresh time for PAPI updates (In Ticks. 20 ticks = 1 second)
  # Recommendation: Set to 20 (1 second) or 60 (3 seconds) for optimal results.
  auto-update-interval: 20

# Configure the inputs used to turn pages.
# Valid options include:
# LEFT, RIGHT, SHIFT_LEFT, SHIFT_RIGHT, WINDOW_BORDER_LEFT, WINDOW_BORDER_RIGHT, MIDDLE, NUMBER_KEY, DOUBLE_CLICK, DROP, CONTROL_DROP, SWAP_OFFHAND
# Note: "SWAP_OFFHAND" is triggered by pressing the 'F' key while hovering over the item.
controls:
  # Inputs to go to the NEXT page (It will loop back to page 1 automatically)
  next-page:
    - "SWAP_OFFHAND"
  # Inputs to go to the PREVIOUS page
  previous-page:
    - "SHIFT_RIGHT"

# Logic parsing for placeholders, allowing dynamic item requirements
# Usage in lore: {check:{papi:placeholder}>=value}
# Example: {check:{papi:mmocore_level}>=105} Combat Level
requirements:
  # Symbol shown when the requirement is MET.
  # Supports MiniMessage formats like <green>, <bold>, <#HexColor>
  met-symbol: "<green>✔"

  # Symbol shown when the requirement is NOT MET.
  # Supports MiniMessage formats like <dark_gray>, <strikethrough>
  unmet-symbol: "<dark_gray>✘"