name: Deploy Wiki

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'docs/wiki/**'
  workflow_dispatch: # Allows you to manually trigger the sync from the GitHub Actions tab

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Folder to GitHub Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: docs/wiki
          token: ${{ secrets.GITHUB_TOKEN }}
          strategy: clone
          disable-empty-commits: true